[package]
name = "edge264_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "edge264_rs"
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.79"
